### ISSUE TITLE
Character encoding for download path

### ISSUE THREAD

**Issue by vmerlet** [YunoHost-Apps/Youtube-dl-WebUI_ynh#1]
When trying this app, I encountered a problem with my download path during installation process :

Choose a folder where video and music will be downloaded : /<something with é character>/
Is it a public application ? (Yes|No) (default: No) :  
Traceback (most recent call last):
  File "/usr/lib/moulinette/yunohost/app.py", line 482, in app_install
    if hook_exec(app_tmp_folder + '/scripts/install', args_dict) == 0:
  File "/usr/lib/moulinette/yunohost/hook.py", line 306, in hook_exec
    arg_str = '\"{:s}\"'.format('\" \"'.join(arg_list))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 48: ordinal not in range(128)
Erreur : Une erreur inattendue est survenue

Note : position 48 is the "é" character.

It seems the app is waiting for 7bit ascii only... would be great to use unicode.

**Comment by rgarrigue** [comment]
This is most likely a yunohost issue in hook.py. I'll try to reproduce it, but I'm afraid I can't do much about it.
